"""Compatibility exports for the canonical ``app.models`` package.

The backend source now owns ORM models under ``app/models``. This module keeps
the historical ``translation_backend.models`` import path working for callers
and existing migrations while avoiding a second model definition.
"""

try:
    from ..app.models import (
        AIProviderCredential,
        AIUsageRecord,
        Document,
        DocumentSegment,
        Project,
        ProjectApiKeyBinding,
        ProjectLanguagePair,
        ProjectMember,
        RefreshToken,
        SegmentLock,
        TimestampedModel,
        User,
        Worldview,
        WorldviewEntry,
        WorldviewEntryRevision,
        TerminologyBase,
        TerminologyTerm,
        TerminologyTermRevision,
        TranslationMemoryLibrary,
        TranslationMemoryEntry,
        TranslationMemoryEntryRevision,
        TranslationMemoryEntrySource,
        TranslationMemoryImport,
    )
except ImportError:
    from app.models import (
        AIProviderCredential,
        AIUsageRecord,
        Document,
        DocumentSegment,
        Project,
        ProjectApiKeyBinding,
        ProjectLanguagePair,
        ProjectMember,
        RefreshToken,
        SegmentLock,
        TimestampedModel,
        User,
        Worldview,
        WorldviewEntry,
        WorldviewEntryRevision,
        TerminologyBase,
        TerminologyTerm,
        TerminologyTermRevision,
        TranslationMemoryLibrary,
        TranslationMemoryEntry,
        TranslationMemoryEntryRevision,
        TranslationMemoryEntrySource,
        TranslationMemoryImport,
    )

__all__ = [
    "AIProviderCredential",
    "AIUsageRecord",
    "Document",
    "DocumentSegment",
    "Project",
    "ProjectApiKeyBinding",
    "ProjectLanguagePair",
    "ProjectMember",
    "RefreshToken",
    "SegmentLock",
    "TimestampedModel",
    "User",
    "Worldview",
    "WorldviewEntry",
    "WorldviewEntryRevision",
    "TerminologyBase",
    "TerminologyTerm",
    "TerminologyTermRevision",
    "TranslationMemoryLibrary",
    "TranslationMemoryEntry",
    "TranslationMemoryEntryRevision",
    "TranslationMemoryEntrySource",
    "TranslationMemoryImport",
]
